server.port: 8081

spring:
  security:
    filter.order: 10
  datasource:
    url: jdbc:h2:file:./.covid.db
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop

logging.level:
  org.springframework: DEBUG
  org.hibernate.SQL: INFO

covidata.url: http://localhost:8080
